[feat] Add Monitoring Details
bandprotocol/bothan pull request #102
Opened 2024-11-21 07:19 UTC by warittornc

## Implementation details
- Do 1
- Do 2

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the GitHub PR explorer)

2024-11-23 15:29 UTC, RogerKSI requested changes

2024-11-23 15:29 UTC, RogerKSI commented on proto/bothan/v1/bothan.proto
> + git // The active sources the Bothan instance is using
is this typo?

2024-11-27 08:33 UTC, colmazia approved these changes

2024-11-27 19:07 UTC, RogerKSI approved these changes

2024-11-28 06:45 UTC, merged