update coinmarketcap source
bandprotocol/bothan pull request #76
Opened 2024-09-25 09:19 UTC by colmazia

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the GitHub PR explorer)

2024-09-26 07:52 UTC, RogerKSI requested changes

2024-09-26 07:52 UTC, RogerKSI commented on bothan-coinmarketcap/src/worker/types.rs
> +pub(crate) const DEFAULT_UPDATE_SUPPORTED_ASSETS_INTERVAL: Duration = Duration::from_secs(86400);
what is this for?

2024-09-26 07:52 UTC, RogerKSI commented on bothan-coinmarketcap/src/worker/types.rs
> +use tokio::time::Duration;
please fix clippy.

2024-09-26 10:42 UTC, warittornc requested changes

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/api/rest.rs
> +        ids: &[&str],
use usize or u32, etc

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/api/rest.rs
>          let ids_string = ids.iter().map(|id| id.to_string()).join(",");
should be able to pass `Vec<(string, usize)>` instead to params

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/worker/opts.rs
> +}
I don't think this is still being used?

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/worker/opts.rs
> +    pub update_supported_assets_interval: Duration,
I don't think this is still being used?

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/worker/builder.rs
> +    }
I don't think this is still being used

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/worker/opts.rs
> +            update_supported_assets_interval: default_update_supported_assets_interval(),
ditto

2024-09-26 10:42 UTC, warittornc commented on bothan-coinmarketcap/src/worker/types.rs
> +pub(crate) const DEFAULT_UPDATE_SUPPORTED_ASSETS_INTERVAL: Duration = Duration::from_secs(86400);
ditto

2024-10-01 09:27 UTC, colmazia commented on bothan-coinmarketcap/src/worker/types.rs
> +pub(crate) const DEFAULT_UPDATE_SUPPORTED_ASSETS_INTERVAL: Duration = Duration::from_secs(86400);
deleted

2024-10-01 09:27 UTC, colmazia commented on bothan-coinmarketcap/src/worker/types.rs
> +use tokio::time::Duration;
fixed

2024-10-01 09:27 UTC, colmazia commented on bothan-coinmarketcap/src/api/rest.rs
> +        ids: &[&str],
fixed

2024-10-01 09:28 UTC, colmazia commented on bothan-coinmarketcap/src/worker/opts.rs
> +}
deleted

2024-10-01 09:28 UTC, colmazia commented on bothan-coinmarketcap/src/worker/opts.rs
> +    pub update_supported_assets_interval: Duration,
deleted

2024-10-01 09:28 UTC, colmazia commented on bothan-coinmarketcap/src/worker/builder.rs
> +    }
deleted

2024-10-01 09:28 UTC, colmazia commented on bothan-coinmarketcap/src/worker/opts.rs
> +            update_supported_assets_interval: default_update_supported_assets_interval(),
deleted

2024-10-02 07:36 UTC, RogerKSI approved these changes

2024-10-03 04:14 UTC, warittornc approved these changes

2024-10-03 09:44 UTC, merged